### ISSUE TITLE
Download flightstack logs using mavlink-router

### ISSUE THREAD

**Issue by kevin-george** [01org/mavlink-router#121]
We are running mavros 0.21 and wish to stream the flightstack logs using mavlink-router over udp. The commands we used were,

`mavlink-routerd -e 127.0.0.1:14550 -l /home/drone/logs /dev/pixhawk:921600`
/dev/pixhawk is the device we mapped using udev rules

`roslaunch mavros px4.launch fcu_url:=udp://@127.0.0.1:14550`

The output of **mavlink-routerd** command was
```
Could not open conf file '/etc/mavlink-router/main.conf' (No such file or directory)
Open UART [4] /dev/pixhawk *
UART [4] speed = 921600
Open UDP [5] 127.0.0.1:14550
Open TCP [6] 0.0.0.0:5760 *
```

The output of **examples/heartbeat-print.py** was
```
HEARTBEAT {type : 14, autopilot : 12, base_mode : 81, custom_mode : 458752, system_status : 3, mavlink_version : 3}
HEARTBEAT {type : 14, autopilot : 12, base_mode : 81, custom_mode : 458752, system_status : 3, mavlink_version : 3}
HEARTBEAT {type : 14, autopilot : 12, base_mode : 81, custom_mode : 458752, system_status : 3, mavlink_version : 3}
```

But when we launch mavros, it doesnt receive anything over the fcu_url.
The output of **rostopic echo /mavros/state**
```
header: 
  seq: 0
  stamp: 
    secs: 1508442258
    nsecs: 642219235
  frame_id: ''
connected: False
armed: False
guided: False
mode: ''
system_status: 0
---
```
**No logs were created either**(We are using a PX4 so .ulog)

Any help in setting this up would be appreciated! :)
